### ISSUE TITLE
ft_strndup : The Game

### ISSUE THREAD

**Issue by YOKOKOYO** [mantal/libft#10]
if n == 0

res = (char *)malloc(sizeof(char) \* n);
Error.

Fix that. Noob.

**Comment by YOKOKOYO** [comment]
Hello

Has it been finally fixed ?

**Comment by mantal** [comment]
<img width="3024" height="4032" alt="Image" src="https://github.com/user-attachments/assets/f141ae57-cc44-41da-bdb1-6e82cf0af500" />
